### ISSUE TITLE
where

### ISSUE THREAD

**Issue by yawnt** [rsdoiel/sqlish#10]
it'd be cool imho if the where clause was written like

``` javascript
where({
  value: { lt: 2 },
  other: { eq: 2}
}) // => WHERE VALUE < 2 AND OTHER=2
```

if you do it this way you can also escape the params (speaking of which how does sqlish handle sql injections?)

^^

// yawn

**Comment by rsdoiel** [comment]
Sqlish's focus is on assembling valid SQL not necessarily preventing injection but I need to think this through.  I like thie idea of using a JSON filter syntax. I need to look into how MongoDB's filter syntax works and see if I can piggyback off that approach or if I should map more specifically to SQL's comparison operators. Need to think about this some more.

**Comment by yawnt** [comment]
i think mongodb's syntax fits pretty nicely and that the lib should provide first class support for data sanitization, but this is just my two cents..

keep up the good work :)

ps: i'm biased because i wanna port a lib of mine to something like sqlish :P

**Comment by rsdoiel** [comment]
First pass at object literals for expression implemented.

**Comment by yawnt** [comment]
it'd be cool imho if instead of "%param" it used something like

``` javascript
/asd/ // => '%ASD%'
/^asd/ // => '%ASD'
/^asd$/ // => 'ASD'
/asd$/ // => 'ASD%'
```

you can get a string of the regex with `.toSource()` i think, check MDN

this is basic stuff, you can get `$` and `^` by chopping or from a substring.. perhaps in the future it would be cool to support also other stuff (`\w+`, etc)
I'd be happy to help...

cheers

// yawn

**Comment by rsdoiel** [comment]
Be happy for the help. Sounds like a good idea.

**Comment by rsdoiel** [comment]
Split this out as a separate issue. Added you as a collaborator and assigned it to you. Let me know if you need anything.
