### ISSUE TITLE
Add defensive parameter validate to all sqlish functions to limit injection vectors

### ISSUE THREAD

**Issue by rsdoiel** [rsdoiel/sqlish#11]
Need to validate all names (e.g. table, column names) as well as things on the right side of the comparison operators. Revalidate if necessary with in toString() before final SQL assembly.

I will need to come up with some injection cases to see if prevention methods actually work.

I may need to limit where strings can be passed in (e.g. select("ID").from("test").where("ID = 2").toString() may not be a good idea anymore).

**Comment by yawnt** [comment]
+1

**Comment by rsdoiel** [comment]
First pass at injection prevention completed. I'm sure their will be additional methods required.

**Comment by yawnt** [comment]
mh i was thinking.. what if you could load a db schema and therefore validation would be available also on insert and stuff? 

something like

``` javascript
sqlish.define('table', { 
  row: Integer({ length: 32})
});
sqlish.createTable('table');
sqlish.insert('table',{
  row: 3,
  row2: 4 // this gets ignored
});

```

it's just an example.. i think this should be considered carefully to improve security but without sacrificing usability

**Comment by rsdoiel** [comment]
I need to think about this.  I'm not sure explicit type validation against a defined schema lowers the risks of injection much more than the implicit type checking provided by safely() and safeName(). I agree that it would prevent
storing the wrong type of data in the wrong column. Since data can be wrong and still the right type I'm not sure you can avoid validating your data before generating your SQL queries.

Think about SELECT statements with JOINs. Would you have to define all tables you're joining against before you could call select()? I would personally hate to have to type schema out of use cases where all I'm doing is a series of complex select().

I'm willing to be convinced otherwise. Maybe I'm not thinking of the use cases the right way but I'd like to keep sqlish minimalalist to use, minimal in size and minimally featured.

**Comment by yawnt** [comment]
that's why i said it has to be considered carefully...
even though i meant to use it mainly on certain occasions (eg insertion).
my use case would be.. you're updating a document from an html form.. it could be nice to be able to do

``` javascript
.insert(table, req.body)
```

instead of whitelisting manually

i do agree that it makes little sense on select (or where etc) where you have tons of options (also think of something like `select('count()')` that'd become impossible) and tons of edge cases

**Comment by rsdoiel** [comment]
Let's leave it for now (by the way, just added your RegExp suggestion) and think about it.  I think you're on the right track but we just need to come up with a way to keep it simple and easy.
