### ISSUE TITLE
Map in RegExp support for handling $like expressions

### ISSUE THREAD

**Issue by rsdoiel** [rsdoiel/sqlish#12]
Implementation would like look

```
 {name: {$like: /^fred/}}  // render as => name LIKE "fred%"
 {name: {$like: /sen$/}}  // render as => name LIKE "%sen"
```

Yawn's suggestion:

```
/asd/ // => '%ASD%'
/^asd/ // => '%ASD'
/^asd$/ // => 'ASD'
/asd$/ // => 'ASD%'
```

**Comment by rsdoiel** [comment]
Need to support both string and RegExp() to save on RegExp object creation for long programs:

```
{$like: /^my stuff/}
{$like: "mu stuff%"}
```

**Comment by rsdoiel** [comment]
Got it working and passing tests.

**Comment by yawnt** [comment]
lol.. i was eating.. i was about to fix the tests... never mind ;P

**Comment by yawnt** [comment]
also did you write tests for the RegExp @rsdoiel ?

lol know i see, you wrote your version.. i published a draft on the regExp branch on this repo
