### ISSUE TITLE
prepared staments

### ISSUE THREAD

**Issue by yawnt** [rsdoiel/sqlish#17]
now i know this is a library to generate sql code.. 
it'd be really useful though to let the user (eg through plugins) alterate the query in order to provide true and flawless sanitization

eg: 
i want to run a query in node-mysql
i load the plugin
sqlish generates a prepared statement through the plugin (`select * from x where l=?`)
sqlish.runQuery (that is defined in the plugin) runs the query and callbacks

**Comment by rsdoiel** [comment]
I like that idea but before we build a plugin system let's get the basic
support for SQL 92',  SQLite3, MySQL 5.5 and PostgreSQL 9.2 working for
common types of queries. I've also been thinking with how I've changed SQL
assembly you might be able to evolve this so as to so something like -

```
sql.select("name").from("my_table").asMongoQuery();
// This would translate into something like db.my_table.find({}, {name:
```

1});

That would be way down the road but it's an idea in the back of my head.
I'll try to wrap up

Thanks,

Robert

**Comment by yawnt** [comment]
fair enough.. let's get this sql done

if we really wanna do the mongo stuff we should try to leverage the language to be as db agnostic as possible and to heavily rely on plugins (which implies a heavy refactoring of the current implementation)

stuff like .mongoQuery could be hidden with a previous `.use({ dialect: 'mongo'})`

**Comment by rsdoiel** [comment]
Yes, that would be a better method and I think rendering (or executing in
the mongo shell) would be a good test/point to implement plugin.

Thanks,

Robert
