### ISSUE TITLE
Implement some date to string convenience functions for date handling and relative date handling

### ISSUE THREAD

**Issue by rsdoiel** [rsdoiel/sqlish#31]
A common thing I run into is needing relative dates or doing repetitive output formatting.  MySQL likes date/times in YYYY-MM-DD HH:MM:SS format as string.  It would be nice to have something like this available -

``` JavaScript
    // these would return JavaScript date objects.
    d1 = relativeDate("+2 weeks", new Date());
    d2 = relativeTime("+2 mins", new Date());
    // Calculate a new date setting it via UTC
    d3 = relativeDateTime("+24 hours", new Date(), true);

    // Now make them SQL friendly
    // Save as date only
    dateToSQL(d1, "DATE");
    // Save as time only
    dateToSQL(d2, "TIME");
    // Save as DATETIME
    dateToSQL(d3, "DATETIME");
```

These could hang directly off the sqlish object.

**Comment by yawnt** [comment]
check out moment.js ..

**Comment by rsdoiel** [comment]
That is very cool.  Now I have to learn how to use git with sub modules :-).
- Robert

**Comment by yawnt** [comment]
i'd just add it to package.json
