### ISSUE TITLE
postgresql support

### ISSUE THREAD

**Issue by yawnt** [rsdoiel/sqlish#9]
this would be a killer feature :)

**Comment by rsdoiel** [comment]
I'll try to start adding support for this dialect in release 0.0.5. May take a little while as I haven't used Postgres in a decade.

**Comment by rsdoiel** [comment]
Been reading through the PostgreSQL 9.2 docs. Looks like integrating support for the dialect should be straight forward. SQLite (which I need to support for browsers) is the smallest subset (also most picky IMO). MySQL and PostgreSQL currently have a large degree of overlap in their support of standard SQL. I don't run PostgreSQL myself so I'd be interested in feed back when I get to that stage. Some support might make it into 0.0.4 release.

**Comment by rsdoiel** [comment]
Started integration. So far what works on MySQL should also work on PostgresSQL. As more SQL generation is supported the differences will become more apparent and sqlish with throw the appropriate errors when their is a conflict.
